export const COPY = {
  nav: {
    accounts: 'Accounts',
    partners: 'Partner',
    deals: 'Deals',
    references: 'Referenzen',
    marketSignals: 'Marktsignale',
    dealDesk: 'Deal Desk',
    match: 'Smart Match',
    insights: 'Insights',
    settings: 'Einstellungen',
  },
  pages: {
    dashboard: 'Home',
    references: 'Referenzen',
    marketSignals: 'Marktsignale',
    dealDesk: 'Deal Desk',
    match: 'Smart Match',
  },
  misc: {
    matches: 'Treffer',
    teamManagement: 'Teamverwaltung',
    workspace: 'Arbeitsbereich',
    firstReference: 'Erste Referenz',
    team: 'Team',
  },
  notifications: {
    title: 'Benachrichtigungen',
    markAllReadAria: 'Alle Benachrichtigungen als gelesen markieren',
    unreadBadgeAria: 'Ungelesen',
  },
  /** Profilmenü: welche Rolle die Oberfläche steuert (Cookie, nur wenn die Umgebung es erlaubt). */
  roleSwitcher: {
    profileMenuSectionTitle: 'Rolle wechseln',
    profileMenuReset: 'Anzeige zurücksetzen',
    profileMenuHint:
      'Steuert nur die Oberfläche. Server und Datenbank nutzen weiterhin deine gespeicherte Profil-Rolle.',
    profileMenuActiveSuffix: 'aktiv',
    roleMarketingAdmin: 'Marketing / Admin',
    roleAccountManager: 'Account Manager',
    roleSalesRep: 'Sales Representative',
    switchSuccess: 'Oberflächen-Rolle aktualisiert.',
  },
  roles: {
    accountManager: 'Account Manager',
    salesManager: 'Sales Manager',
    readOnly: 'Nur Lesen',
  },
  roleDimensions: {
    systemRoles: {
      owner: 'Inhaber',
      admin: 'Administrator',
      member: 'Mitglied',
      viewer: 'Betrachter',
    },
    functionRoles: {
      sales_rep: 'Vertrieb',
      account_manager: 'Account Manager',
      sales_leader: 'Sales Lead',
    },
  },
  settings: {
    accountDeletionNotAvailableHint:
      'Kontolöschung ist aktuell nicht als Self-Service verfügbar.',
    accountDeletionDisabledToast:
      'Kontolöschung ist derzeit nicht aktiviert. Bitte wende dich an den Support, wenn du den Workspace schließen möchtest.',
    teamInviteEmailSent: 'Einladung wurde per E-Mail versendet.',
    teamInviteSavedEmailMissingKey:
      'Einladung ist gespeichert, aber E-Mail-Versand ist nicht konfiguriert (RESEND_API_KEY in der Server-Umgebung).',
    teamInviteSavedEmailFailed:
      'Einladung ist gespeichert, die E-Mail konnte nicht versendet werden.',
    teamInviteCopyLink: 'Einladungslink kopieren',
    teamInviteLinkCopied: 'Einladungslink in die Zwischenablage kopiert.',
    roleSwitcherTab: 'Entwicklung',
    roleSwitcherCardTitle: 'Rollenauswahl (Entwicklung)',
    roleSwitcherCardDescription:
      'Legt fest, welche Rolle die Oberfläche steuert (Cookie). Viele Aktionen auf dem Server prüfen weiterhin deine gespeicherte Profil-Rolle in der Datenbank.',
    roleSwitcherStoredLabel: 'Rolle in der Datenbank',
    roleSwitcherActiveLabel: 'Rolle in der Oberfläche',
    roleSwitcherPickLabel: 'Als folgende Rolle anzeigen',
    roleSwitcherReset: 'Anzeige zurücksetzen',
    rolesPermissions: {
      title: 'Rollen & Rechte',
      description:
        'Org-weite Vorgaben für Sichtbarkeit und Freigabe. Ohne Konfiguration gelten die Standardwerte aus dem Rollenmodell.',
      salesSeesDraftsLabel: 'Vertrieb sieht Entwürfe',
      salesSeesDraftsHint:
        'Wenn aktiv, dürfen Vertriebsmitglieder (sales_rep) Entwürfe in der Datenbank sehen — wirkt in RLS und Suche.',
      visibilityMatrixTitle: 'Sichtbarkeit nach Funktions-Rolle',
      approvalRoutingLabel: 'Freigabe-Routing',
      approvalRoutingHint:
        'Gespeicherte Vorgabe für künftige Workflow-Anbindung. Bestehende Freigabe-Flows bleiben unverändert, bis sie daran angebunden werden.',
      approvalRouting: {
        am_direct: 'Account Manager → Kunde',
        via_rpm: 'Über Reference Program Manager',
        legal_gate_on_nda: 'Legal-Gate bei NDA',
      },
      sensitivityDraft: 'Label Entwurf',
      sensitivityNda: 'Label NDA',
      sensitivityConfidential: 'Label vertraulich (Sales)',
      save: 'Speichern',
      saveSuccess: 'Rollen & Rechte gespeichert.',
      capabilities: {
        see_draft_references: 'Entwürfe sehen',
        see_confidential_references: 'Vertrauliche Referenzen sehen',
      },
    },
    capabilityProfile: {
      title: 'Fähigkeitsprofil & ICP',
      description:
        'Quantifizierte Org-Daten für den automatischen Eignungs-/K.O.-Check auf RFP-Deals. Leeres Profil → alle Kriterien „Unbekannt".',
      emptyHint:
        'Profil ist leer — der K.O.-Check wertet Kriterien konservativ als „Unbekannt", niemals als still bietfähig.',
      employeeCount: 'Mitarbeiterzahl',
      annualRevenue: 'Jahresumsatz (Mio €)',
      regions: 'Regionen (kommagetrennt)',
      certifiedRoles: 'Zertifizierte Rollen (eine Zeile pro Rolle: Name:Anzahl)',
      icpTitle: 'ICP-Rubrik (5 Felder)',
      icpIndustry: 'Branche',
      icpVolume: 'Volumen-Band',
      icpRegion: 'Region',
      icpAccountSize: 'Firmengröße Account',
      icpSegment: 'Segment',
      save: 'Profil speichern',
      saving: 'Speichern …',
      saved: 'Fähigkeitsprofil gespeichert.',
      readOnly: 'Nur Workspace-Administratoren können das Profil bearbeiten.',
    },
  },
  table: {
    empty: 'Keine Ergebnisse.',
    rowsPerPage: 'Ergebnisse pro Seite',
    columns: 'Spalten',
    view: 'Ansicht',
  },
  references: {
    contextSelect: 'Selektieren',
    contextOpen: 'Öffnen',
    contextEdit: 'Bearbeiten',
    filterReferencesPlaceholder: 'Referenzen filtern…',
  },
  deals: {
    contextSelect: 'Selektieren',
    contextOpen: 'Deal öffnen',
    contextOpenNewTab: 'In neuem Tab öffnen',
    searchPlaceholder: 'Deals durchsuchen (Titel, Account, AM) …',
    newDealButton: 'Deal anlegen',
    filterStatusAll: 'Alle Status',
    filterStatusNegotiation: 'Verhandlung',
    filterStatusRfp: 'RFP-Phase',
    filterStatusWon: 'Gewonnen',
    filterStatusLost: 'Verloren',
    referenceCountColumn: 'Referenzen',
    matchColumn: 'Match',
    /** Labels im Menü „Spalten“ (Deals-Tabelle). */
    columnViewLabels: {
      status: 'Status',
      title: 'Titel',
      company_name: 'Account',
      volume: 'Volumen',
      reference_count: '# Referenzen',
      match: 'Match',
      expiry_date: 'Ablauf',
      account_manager_name: 'Account Manager',
      sales_manager_name: 'Sales Manager',
    },
    cockpit: {
      factsTitle: 'Deal-Fakten',
      crmStage: 'CRM-Stage',
      crmOpportunity: 'Opportunity',
      openInCrm: (provider: string) => `In ${provider} öffnen`,
      activityTitle: 'Aktivität',
      actionsMenu: 'Aktionen',
      generateBriefing: 'Briefing erzeugen',
      promoteToRfp: 'Als Ausschreibung bearbeiten',
      demoteFromRfp: 'Kein Ausschreibungs-Deal',
      rfpBlockPlaceholder: 'Ausschreibungs-Analyse folgt in den nächsten Schritten.',
      proofTitle: 'Referenzen am Deal',
      proofEmpty: 'Noch keine Referenzen verknüpft — finde passende Beweise für diesen Deal.',
      findReference: 'Referenz finden',
      findReferenceTitle: 'Referenz finden',
      findReferenceDescription:
        'Smart Search und RFP-Coverage mit vorausgefülltem Deal-Kontext. Treffer können direkt verknüpft werden.',
      deadlinesEmpty: 'Keine Termine',
      deadlinesEmptyHint:
        'Fristen erscheinen nach RFP-Analyse oder wenn du manuell Termine hinzufügst.',
      addDeadline: 'Termin',
      editDeadline: 'Termin bearbeiten',
      rfpBlockTitle: 'Ausschreibung',
      rfpBlockSubtitle: 'Metriken und Eignungs-Check aus der letzenden RFP-Analyse.',
      rfpBlockEmpty:
        'Lade eine Ausschreibung unter Dokumente hoch und starte die Analyse von dort.',
      rfpAnalyzeCta: 'Zu Dokumenten',
      documentsAnalyze: 'Analysieren',
      documentsReanalyze: 'Neu analysieren',
      documentsAnalyzePending: 'Analyse läuft …',
      documentsAnalyzeSuccess: 'RFP-Analyse abgeschlossen.',
      documentsAnalyzeFailed: 'RFP-Analyse fehlgeschlagen.',
      deleteDeal: 'Deal löschen',
      deleteDealConfirm: 'Deal endgültig löschen?',
      deleteDealDescription:
        'Der Deal, alle Dokumente, Fristen und Analyse-Daten werden unwiderruflich entfernt.',
      deleteDealPending: 'Wird gelöscht …',
      deleteDealSuccess: 'Deal gelöscht.',
      deleteDealFailed: 'Deal konnte nicht gelöscht werden.',
      documentsKindChangeAnalysisHint:
        'Analyse basiert auf einer früheren Ausschreibungs-Version dieses Dokuments.',
      metricsStaleHint: 'Neu analysieren, um belastbare Werte zu sehen.',
      metricAngebotsReife: 'Angebots-Reife',
      metricEligibility: 'Bietfähigkeit / Eignung',
      metricEligibilityHint: 'Abgleich RFP-Schwellen mit Fähigkeitsprofil.',
      metricEligibilityEmptyProfile:
        'Fähigkeitsprofil fehlt — K.O.-Check zeigt „Unbekannt", kein stiller Go.',
      eligibilityTitle: 'Eignungs- / K.O.-Check',
      eligibilitySubtitle: 'Quantifizierte Ausschreibungs-Schwellen vs. Org-Profil.',
      eligibilityEmpty: 'Keine strukturierten Eignungskriterien in der Analyse — ggf. neu analysieren.',
      eligibilityColCriterion: 'Kriterium',
      eligibilityColRequirement: 'Prüfung',
      eligibilityColStatus: 'Status',
      eligibilityMandatory: 'Pflicht',
      eligibilityVerdict: 'Gesamtverdikt',
      eligibilityProfileCta: 'Fähigkeitsprofil ergänzen',
      risksTitle: 'Risiken & offene Klärungen',
      risksSubtitle: 'Vertrags-Risiken und fachliche SME-Punkte aus der RFP-Analyse.',
      risksRedFlagsTitle: 'Vertrags-Risiken (Red Flags) · {count}',
      risksRedFlagsEmpty: 'Keine kritischen Vertragsrisiken erkannt.',
      risksSmeTitle: 'Offene fachliche Klärungen · {count}',
      risksSmeEmpty: 'Keine offenen Punkte — alle Anforderungen fachlich abgedeckt.',
      risksSmePointSingular: 'Punkt',
      risksSmePointPlural: 'Punkte',
      draftsTitle: 'Antwort-Entwürfe',
      draftsSubtitle: 'Vorbereitete Antworten pro RFP-Anforderung — mit Referenz-Nachweis.',
      draftsEmpty: 'Noch keine Entwürfe — nach RFP-Analyse oder Neu-Analyse erscheinen sie hier.',
      draftsGenerateCta: '✦ KI-Antwort generieren',
      draftsNoReference: 'Keine verifizierte Referenz — Antwort kann nicht automatisch belegt werden.',
      briefingDialogTitle: 'Executive Briefing',
      briefingDialogDescription:
        'Kompakte Bid-Zusammenfassung für interne Freigabe (Management, ohne Qualification Call).',
      briefingCopyCta: 'Alles kopieren',
      briefingCopied: 'Executive Briefing in die Zwischenablage kopiert.',
      briefingCopyFailed: 'Kopieren fehlgeschlagen.',
      briefingPdfCta: 'Als PDF',
      briefingPdfPending: 'PDF wird erstellt …',
      briefingPdfSuccess: 'Executive Briefing als PDF heruntergeladen.',
      briefingPdfFailed: 'PDF-Export fehlgeschlagen.',
      metricIcpFit: 'ICP-Fit',
      icpPlaceholder: 'Rubrik-basierte ICP-Bewertung folgt.',
      documentsTitle: 'Dokumente',
      documentsEmpty:
        'Noch keine Dokumente — RFP, NDA, Vertrag, Angebot oder andere Dateien hochladen.',
      documentsUpload: 'Hochladen',
      documentsUploadTitle: 'Dokument hochladen',
      documentsKindLabel: 'Dokumenttyp',
      documentsDropzoneHint: 'Datei hierher ziehen oder klicken',
      documentsDropzoneReplace: 'Klicken oder ziehen zum Ersetzen',
      documentsDownload: 'Download',
      documentsRename: 'Umbenennen',
      documentsChangeKind: 'Typ ändern',
      documentsDelete: 'Löschen',
      documentsDeleteConfirm: 'Dokument endgültig löschen?',
      documentsRenameTitle: 'Dateiname',
    },
  },
  accounts: {
    searchCompaniesPlaceholder: 'Firma suchen …',
    searchPartnersPlaceholder: 'Partner suchen …',
    addAccount: 'Account hinzufügen',
    addPartner: 'Partner hinzufügen',
    bulkUploadTooltip:
      'Accounts aus Excel- oder CSV-Datei importieren (Spalten z. B. Name, Website, Branche).',
    bulkUploadTooltipPartner:
      'Partner aus Excel- oder CSV-Datei importieren (Spalten z. B. Name, Website, Kategorie).',
    importTemplateDownload: 'Excel-Vorlage herunterladen',
    importCancel: 'Abbrechen',
    importRemoveFile: 'Datei entfernen',
    importInvalidFile: 'Bitte eine CSV- oder Excel-Datei (.csv, .xlsx, .xls) wählen.',
    importInProgress: 'Import läuft …',
    importAccount: {
      title: 'Accounts importieren',
      description:
        'Pro Zeile reicht der Firmenname in Spalte A — Website, Branche, Standort, Logo und Mitarbeiterzahl werden beim Import per Brandfetch ergänzt. Weitere Spalten sind optional.',
      dropzoneTitle: 'CSV oder Excel hierher ziehen',
      dropzoneHint: 'oder klicken, um eine Datei vom Gerät zu wählen',
      fileSelectedHint: 'Klicken oder ziehen zum Ersetzen',
      submit: 'Importieren',
    },
    importPartner: {
      title: 'Partner importieren',
      description:
        'Pro Zeile reicht der Name in Spalte A (optional Kategorie in F: sub, tech, legal, other). Alle anderen Felder werden per Brandfetch ergänzt.',
      dropzoneTitle: 'CSV oder Excel hierher ziehen',
      dropzoneHint: 'oder klicken, um eine Datei vom Gerät zu wählen',
      fileSelectedHint: 'Klicken oder ziehen zum Ersetzen',
      submit: 'Importieren',
    },
    tooltipFilter: 'Filtern',
    tooltipFavorites: 'Favoriten',
    alsoLinkedAccountHint: 'Auch als Account verknüpft',
    ariaFavoritesOnlyOn: 'Nur Favoriten anzeigen',
    ariaFavoritesOnlyOff: 'Alle Accounts anzeigen',
    createDialogNameHint:
      'Firmennamen eingeben — Vorschläge aus euren Accounts, Partnern und Markendaten erscheinen beim Tippen.',
    createDialogSuggestLocal: 'Bereits angelegt',
    createDialogSuggestBrandfetch: 'Markenvorschlag',
    createDialogSearching: 'Suche nach Firmennamen …',
    createDialogTypeMore: 'Mindestens 2 Zeichen für die Namenssuche eingeben.',
    createDialogNoResults:
      'Keine Treffer für diesen Namen. Namen weiter ausformulieren oder unten manuell anlegen.',
    createDialogBrandfetchHint:
      'Markendaten vorübergehend nicht verfügbar. Bitte kurz warten oder Stammdaten manuell ausfüllen.',
    createDialogOpenExisting: 'Dieser Account existiert bereits. Es wird zur Detailseite gewechselt.',
    editDialogTitle: 'Account bearbeiten',
    editSuccess: 'Account gespeichert.',
    editButton: 'Bearbeiten',
    quickCreateAccountTitle: 'Neuen Account anlegen',
    quickCreateAccountSubmit: 'Account anlegen und auswählen',
    quickCreateAccountHint:
      'Legt einen Account in deiner Organisation an und wählt ihn für diesen Deal aus.',
  },
  dashboard: {
    searchReferencesPlaceholder: 'Referenzen suchen...',
    columnsToggleAria: 'Spalten ein-/ausblenden',
    tooltipFavorites: 'Favoriten',
    tooltipStatus: 'Status',
    tooltipColumns: 'Spalten',
    tooltipImport: 'Importieren',
    tooltipCreateReference: 'Referenz erstellen',
    home: {
      thinBanner:
        'Ehrliche Daten: Pre-Pilot — zu wenig Volumen für belastbare Zahlen. Arbeitsschlange bleibt, Kennzahlen erst mit echten Daten.',
      shellGreeting: 'Hallo',
      shellGreetingFallback: 'du',
      signalPillChance: 'Chance',
      signalPillRisk: 'Risiko',
      signalPillCritical: 'kritisch',
      statusCurrent: 'aktuell',
      statusExpiring: 'läuft ab',
      statusStale: 'veraltet',
      periodicQuarter: 'Quartal',
      salesRep: {
        subtitle: 'Deine Arbeit heute.',
        cta: '＋ Referenz finden',
        queueTitle: 'Braucht dich jetzt',
        queueDescription: 'Nach Dringlichkeit — was deine Deals heute voranbringt.',
        queueEmptyTitle: 'Leg los',
        queueEmptyDescription:
          'Verknüpfe deinen ersten Beweis mit einem offenen Deal — dann taucht hier deine Arbeitsschlange auf.',
        queueNoProof: 'kein Beweis',
        queueWeakProof: 'schwach belegt',
        queueFindProof: 'Beweis finden',
        queueHotSignal: 'heißes Signal',
        queueFollowUp: 'nachfassen',
        queueSnoozeBack: 'Signale aus Snooze zurück',
        queueSnoozeDue: 'Wiedervorlage fällig',
        queueReview: 'Review Queue',
        dealOpen: 'offen',
        dealOverdue: 'überfällig',
        dealToday: 'heute',
        dealInOneDay: 'in 1 Tag',
        dealInDays: 'in {n} Tagen',
        dealInOneWeek: 'in 1 Wo',
        dealInWeeks: 'in {n} Wo',
        signalsTitle: 'Signale zu deinen Accounts',
        signalsDescription:
          'News und Positionswechsel bei deinen Accounts — jeweils mit passender Reaktion.',
        signalsEmptyTitle: 'Keine Signale',
        signalsEmptyDescription: 'Noch keine überwachten Accounts — Watchlist einrichten.',
        coverageTitle: 'Deine offenen Deals — Beweis-Abdeckung',
        coverageDescription: 'Nach Frist sortiert. Deals ohne Beweis mit direktem Link.',
        coverageEmptyTitle: 'Noch keine Deals verknüpft',
        coverageEmptyDescription: '',
        coverageDonutSublabel: 'mit Beweis',
        coverageProofOk: 'Beweis ✓',
        coverageUntil: 'bis',
        reuseTitle: 'Was bei dir zieht',
        reuseDescription: 'Deine häufigsten Shares — Gewinner wiederverwenden.',
        reuseEmptyTitle: 'Noch nichts geteilt',
        reuseEmptyDescription: '',
        reuseFallbackTitle: 'Referenz',
        footerLabel: 'Diese Woche',
        footerMatches: '{n} Matches',
        footerShared: '{n} geteilt',
        footerDealsProof: '{withProof}/{total} Deals belegt',
        footerNoDeals: '0 Deals belegt',
        footerThinMatches: '0 Matches',
        footerThinShared: '0 geteilt',
        footerThinDeals: '0/0 Deals belegt',
      },
      accountManager: {
        subtitle: 'Was in deinem Portfolio Aufmerksamkeit braucht.',
        cta: '＋ Referenz erstellen',
        digestTitle: 'Wartet auf dich',
        digestDescription: 'Digest — was dich braucht.',
        digestEmptyTitle: 'Alles erledigt',
        digestEmptyDescription: 'Keine offenen Freigaben oder Anfragen.',
        digestApprovals: '{n} Referenzen warten auf deine Freigabe',
        digestApprovalsMeta: 'älteste seit {days} Tagen',
        digestApprovalsCta: 'freigeben',
        digestDealRequests: '{n} neue Referenz-Anfragen aus Deals',
        digestDealRequestsCta: 'bearbeiten',
        digestAdvocateWarn: 'Advocate-Warnung: {company}',
        digestAdvocateMeta: 'Fatigue-Schwelle erreicht',
        digestAdvocateCta: 'Quartal pausieren',
        freshTitle: 'Portfolio-Gesundheit — Frische',
        freshDescription: 'Was veraltet, läuft ab oder braucht Update?',
        freshEmptyTitle: 'Noch kein Portfolio',
        freshEmptyDescription: '',
        freshMore: '{n} weitere',
        freshMoreSub: 'aktuell',
        whitespotTitle: 'Weißflecken — was fehlt',
        whitespotDescription: 'Branchen/Themen ohne belastbare Referenz.',
        whitespotEmptyTitle: 'Noch keine Abdeckung',
        whitespotEmptyDescription: '',
        whitespotRequest: 'anfragen',
        funnelTitle: 'Freigabe-Durchsatz',
        funnelDescription: 'Wo stehen Referenzen im Flow?',
        funnelEmptyTitle: 'Noch keine Referenzen',
        funnelEmptyDescription: '',
        funnelDraft: 'Entwurf',
        funnelInternal: 'Intern geprüft',
        funnelCustomer: 'An Kunde',
        funnelApproved: 'Freigegeben',
        advocateTitle: 'Advocate-Last',
        advocateDescription: 'Wen frage ich wie oft?',
        advocateEmptyTitle: 'Noch keine Anfragen',
        advocateEmptyDescription: '',
        footerLabel: 'Dein Portfolio',
        footerReferences: '{n} Referenzen',
        footerPending: '{n} Freigaben offen',
        footerAdvocate: '{n} Advocate-Anfragen',
      },
      salesLeader: {
        subtitle: 'Was steht heute auf dem Plan?',
        cta: 'Team-Report',
        riskTitle: 'Deals mit Risiko — Beweis-Abdeckung',
        riskDescription: 'Offene Deals nach Wert und Frist, bewertet nach Beweislage.',
        riskEmptyTitle: 'Noch zu wenige Deals',
        riskEmptyDescription: 'Eine belastbare Risiko-Sicht braucht mehr offene Deals im System.',
        riskNoProof: 'kein Beweis',
        riskPartial: 'teilweise',
        riskStrong: 'stark belegt',
        riskWeakCount: 'schwach belegt ({n}/{total})',
        riskPushRep: 'Rep pushen',
        riskRequestRef: 'Referenz anfragen',
        riskReview: 'prüfen',
        coachingTitle: 'Coaching-Signal',
        coachingDescription: 'Wer nutzt die Beweis-Arbeit — wer braucht einen Impuls?',
        coachingEmptyTitle: 'Zu wenig Nutzung',
        coachingEmptyDescription: 'Adoption noch niedrig — CS-Begleitung im Pilot.',
        covPipeTitle: 'Abdeckung vs. Pipeline',
        covPipeDescription: 'Wo verfolgen wir Deals, für die uns der Beweis fehlt?',
        covPipeEmptyTitle: 'Noch keine Pipeline-Abdeckung',
        covPipeEmptyDescription: '',
        signalRiskTitle: 'Signal-Risiko in der Pipeline',
        signalRiskDescription: 'Beziehungs- und Trigger-Risiko über offene Deals.',
        signalRiskEmptyTitle: 'Zu wenig Daten',
        signalRiskEmptyDescription: 'Signal-Risiko braucht mehr überwachte Accounts und Deals.',
        signalRiskIntervene: 'eingreifen',
        signalRiskPushTeam: 'Team anstoßen',
        winTitle: 'Wirkungs-Beleg',
        winDescription: 'ROI-Beleg für die Leitung — bewusst periodisch, nicht operativ.',
        winEmptyTitle: 'Noch nicht aussagekräftig',
        winEmptyDescription: '{closed} abgeschlossene Deals (Schwelle: {min}). Kein Fake-Chart.',
        winWithRef: 'mit Referenz',
        winWithoutRef: 'ohne Referenz',
        winDelta: 'Δ +{n} Prozentpunkte Win-Rate',
        footerLabel: 'Org',
        footerReferences: '{n} Referenzen',
        footerActiveUsers: '{n} aktive Nutzer',
        footerShareRate: '{n}% Share-Rate',
      },
    },
  },
  marketSignals: {
    pageSubtitle: 'Deine Account-Intelligenz auf einen Blick',
    signalTypeExec: 'Exec Update',
    signalTypeCompany: 'Company Update',
    executiveSection: 'Executive Tracking',
    newsSection: 'Company Update',
    championSection: 'Executive Tracking',
    manage: 'Verwalten',
    filterAccount: 'Account filtern',
    filterSegmentLabel: 'Typ',
    allAccounts: 'Alle Accounts',
    segmentAll: 'Alle',
    segmentCustomers: 'Kunden',
    segmentProspects: 'Prospects',
    newBadge: 'Neu',
    openAccount: 'Zum Account',
    sourcePrefix: 'Quelle',
    loadMore: '10 weitere anzeigen',
    emptyFollowingTitle: 'Noch keine Accounts in deiner Watchlist',
    emptyFollowingBody: 'Start tracking your accounts to see signals here.',
    emptyFollowingCta: 'Accounts verwalten',
    executiveEmptyTitle: 'Noch keine Führungswechsel',
    executiveEmptyBody:
      'In Phase 1 werden Einträge manuell gepflegt oder per CSV importiert. Anschließend erscheinen sie hier.',
    newsEmptyTitle: 'Noch keine Company Updates',
    newsEmptyBody:
      'In Phase 1 werden Meldungen als Notizen je Account erfasst. Automatische Quellen folgen später.',
    roleChangeArrow: '→',
  },
  commandPalette: {
    title: 'Command Palette',
    description: 'Suche nach Referenzen, Accounts oder Deals',
    placeholder: 'Suche nach Referenzen, Deals, Accounts…',
    searchLoading: 'Suche läuft…',
    searchEmpty: 'Keine Ergebnisse gefunden.',
    quickActions: 'Schnellaktionen',
    recents: 'Zuletzt besucht',
    noRecentsYet: 'Noch keine Einträge',
    actionStartMatch: 'Suche starten',
    actionNewDeal: 'Neuen Deal erstellen',
    actionNewReference: 'Neue Referenz erstellen',
    actionNewAccount: 'Account erstellen',
    /** Anzeige in der Suche, wenn keine Firma verknüpft ist */
    referenceNoAccountLabel: 'Kein Accountname vergeben',
  },
} as const

/** Tabellen: Auswahl-Zeile („3 von 10 Zeilen ausgewählt“). */
export function copyTableRowsSelected(selected: number, total: number) {
  return `${selected} von ${total} Ergebnissen ausgewählt`
}

