export const COPY = {
  nav: {
    accounts: 'Accounts',
    deals: 'Deals',
    dealsExpandAria: 'Deine Deals aufklappen',
    dealsCollapseAria: 'Deine Deals zuklappen',
    dealsMineEmpty: 'Keine eigenen aktiven Deals',
    references: 'Referenzen',
    marketSignals: 'Marktsignale',
    match: 'Smart Match',
  },
  pages: {
    dashboard: 'Home',
  },
  misc: {
    workspace: 'Arbeitsbereich',
  },
  notifications: {
    title: 'Benachrichtigungen',
    markAllReadAria: 'Alle Benachrichtigungen als gelesen markieren',
    unreadBadgeAria: 'Ungelesen',
    unreadCount: '{count} ungelesen',
    tabSignals: 'Signale',
    tabApprovals: 'Freigaben',
    tabOther: 'Sonstiges',
    empty: 'Keine Benachrichtigungen.',
    emptyTab: 'Keine Einträge in dieser Kategorie.',
  },
  /** Profilmenü: welche Rolle die Oberfläche steuert (Cookie, nur wenn die Umgebung es erlaubt). */
  roleSwitcher: {
    profileMenuSectionTitle: 'Rolle wechseln',
    profileMenuReset: 'Anzeige zurücksetzen',
    profileMenuHint:
      'Steuert nur die Oberfläche. Server und Datenbank nutzen weiterhin deine gespeicherte Profil-Rolle.',
    profileMenuActiveSuffix: 'aktiv',
    switchSuccess: 'Oberflächen-Rolle aktualisiert.',
  },
  roles: {
    accountManager: 'Account Manager',
    salesManager: 'Sales Manager',
  },
  roleDimensions: {
    systemRoles: {
      owner: 'Inhaber',
      admin: 'Administrator',
      member: 'Mitglied',
      viewer: 'Betrachter',
    },
    functionRoles: {
      sales_rep: 'Sales Rep',
      account_manager: 'Account Manager',
      sales_leader: 'Sales Lead',
    },
  },
  settings: {
    dangerZoneTitle: 'Gefahrenzone',
    deleteAccountButton: 'Konto löschen',
    deleteAccountBody: 'Konto dauerhaft löschen.',
    deleteAccountTitle: 'Konto wirklich löschen?',
    teamInviteEmailSent: 'Einladung wurde per E-Mail versendet.',
    teamInviteSavedEmailMissingKey:
      'Einladung ist gespeichert, aber E-Mail-Versand ist nicht konfiguriert (RESEND_API_KEY in der Server-Umgebung).',
    teamInviteSavedEmailFailed:
      'Einladung ist gespeichert, die E-Mail konnte nicht versendet werden.',
    teamInviteCopyLink: 'Einladungslink kopieren',
    teamInviteLinkCopied: 'Einladungslink in die Zwischenablage kopiert.',
    teamOwnRoleDisabledHint: 'Deine eigene Rolle kannst du hier nicht ändern.',
    teamRemoveMemberTooltip: 'Mitglied entfernen',
    exportAsCsv: 'Als CSV exportieren',
    signOutOtherDevices: 'Andere Geräte abmelden',
    signOutEverywhere: 'Überall abmelden',
    signOutEverywhereTitle: 'Überall abmelden?',
    signOutEverywhereDescription:
      'Du wirst auf allen Geräten abgemeldet, auch auf diesem.',
    roleSwitcherCardTitle: 'Rollenauswahl (Entwicklung)',
    roleSwitcherStoredLabel: 'Rolle in der Datenbank',
    roleSwitcherActiveLabel: 'Rolle in der Oberfläche',
    roleSwitcherPickLabel: 'Als folgende Rolle anzeigen',
    roleSwitcherReset: 'Anzeige zurücksetzen',
    rolesPermissions: {
      title: 'Rollen & Rechte',
      salesSeesDraftsLabel: 'Sales Rep sieht Entwürfe',
      salesSeesDraftsHint:
        'Wenn aktiv, dürfen Sales Reps Entwürfe in der Datenbank sehen — wirkt in RLS und Suche.',
      visibilityMatrixTitle: 'Sichtbarkeit nach Funktions-Rolle',
      approvalRoutingLabel: 'Freigabe-Routing',
      approvalRoutingHint:
        'Gespeicherte Vorgabe für künftige Workflow-Anbindung. Bestehende Freigabe-Flows bleiben unverändert, bis sie daran angebunden werden.',
      approvalRouting: {
        am_direct: 'Account Manager → Kunde',
        via_rpm: 'Über Reference Program Manager',
        legal_gate_on_nda: 'Legal-Gate bei NDA',
      },
      sensitivityDraft: 'Label Entwurf',
      sensitivityNda: 'Label NDA',
      sensitivityConfidential: 'Label vertraulich (Sales)',
      save: 'Speichern',
      saveSuccess: 'Rollen & Rechte gespeichert.',
      capabilities: {
        see_draft_references: 'Entwürfe sehen',
        see_confidential_references: 'Vertrauliche Referenzen sehen',
      },
    },
    capabilityProfile: {
      title: 'Fähigkeitsprofil & ICP',
      description:
        'Quantifizierte Org-Daten für den automatischen Eignungs-/K.O.-Check auf RFP-Deals. Leeres Profil → alle Kriterien „Unbekannt".',
      emptyHint:
        'Profil ist leer — der K.O.-Check wertet Kriterien konservativ als „Unbekannt", niemals als still bietfähig.',
      employeeCount: 'Mitarbeiterzahl',
      annualRevenue: 'Jahresumsatz (Mio €)',
      regions: 'Regionen (kommagetrennt)',
      certifiedRoles: 'Zertifizierte Rollen (eine Zeile pro Rolle: Name:Anzahl)',
      icpTitle: 'ICP-Rubrik (5 Felder)',
      icpIndustry: 'Branche',
      icpVolume: 'Volumen-Band',
      icpRegion: 'Region',
      icpAccountSize: 'Firmengröße Account',
      icpSegment: 'Segment',
      save: 'Profil speichern',
      saving: 'Speichern …',
      saved: 'Fähigkeitsprofil gespeichert.',
      readOnly: 'Nur Workspace-Administratoren können das Profil bearbeiten.',
    },
  },
  table: {
    empty: 'Keine Ergebnisse.',
    rowsPerPage: 'Ergebnisse pro Seite',
  },
  references: {
    contextSelect: 'Selektieren',
    contextOpen: 'Öffnen',
    contextEdit: 'Bearbeiten',
    exportAsPdf: 'Als PDF exportieren',
    exportAsPptx: 'Als PPTX exportieren',
    exportAsPptxPending: 'PPTX wird erstellt…',
  },
  deals: {
    contextOpen: 'Deal öffnen',
    contextOpenNewTab: 'In neuem Tab öffnen',
    searchPlaceholder: 'Deals durchsuchen (Titel, Account, AM) …',
    newDealButton: 'Deal anlegen',
    filterStatusAll: 'Alle Status',
    filterStatusNegotiation: 'Verhandlung',
    filterStatusRfp: 'RFP-Phase',
    filterStatusWon: 'Gewonnen',
    filterStatusLost: 'Verloren',
    proofColumn: 'Beweislage',
    deadlineColumn: 'Frist',
    /** Labels im Menü „Spalten“ (Deals-Tabelle). */
    columnViewLabels: {
      status: 'Status',
      title: 'Titel',
      company_name: 'Account',
      volume: 'Volumen',
      proof: 'Beweislage',
      expiry_date: 'Frist',
      account_manager_name: 'Account Manager',
      sales_manager_name: 'Sales Manager',
    },
    cockpit: {
      factsTitle: 'Deal-Fakten',
      factsEditAria: 'Deal-Fakten bearbeiten',
      deleteDeadlineAria: 'Termin entfernen',
      stammdatenTitle: 'Stammdaten',
      stammdatenEmpty:
        'Noch keine Stammdaten — nach der Analyse erscheinen Auftraggeber, Fristen und Eckdaten hier.',
      stammdatenFields: {
        customer: 'Auftraggeber',
        documents: 'Einzureichende Unterlagen',
        location: 'Standort',
        volume: 'Budget / Volumen',
        submissionDeadline: 'Einreichungsfrist',
        serviceStart: 'Leistungsbeginn',
        procedure: 'Verfahren',
        contact: 'Ansprechpartner',
        techFocus: 'Technik-Fokus',
        governance: 'Governance / Compliance',
        qualifications: 'Erforderliche Qualifikationen',
        roles: 'Rollen / Profile',
        domains: 'Domänen',
        specialConditions: 'Besondere Bedingungen',
      },
      actionsMenu: 'Aktionen',
      generateBriefing: 'Briefing erzeugen',
      promoteToRfp: 'Als Ausschreibung bearbeiten',
      demoteFromRfp: 'Kein Ausschreibungs-Deal',
      proofTitle: 'Verknüpfte Referenzen',
      proofEmpty:
        'Noch keine Referenzen verknüpft — finde passende Beweise für diesen Deal.',
      proofRemoveAria: 'Referenz aus Deal entfernen',
      findReference: 'Referenz finden',
      findReferenceTitle: 'Referenz finden',
      findReferenceDescription:
        'Smart Search und RFP-Coverage mit vorausgefülltem Deal-Kontext. Treffer können direkt verknüpft werden.',
      nextDeadlineLabel: 'Nächste Frist',
      deadlinesEmpty: 'Keine Termine',
      ausschreibungNavDokumente: 'Dokumente',
      ausschreibungNavSteckbrief: 'Steckbrief',
      ausschreibungNavStammdaten: 'Stammdaten',
      ausschreibungNavLose: 'Lose',
      ausschreibungNavEignung: 'Eignung',
      ausschreibungNavRisiken: 'Risiken',
      ausschreibungNavDrafts: 'Entwürfe',
      deadlinesEmptyHint:
        'Fristen erscheinen nach RFP-Analyse oder wenn du manuell Termine hinzufügst.',
      addDeadline: 'Termin',
      editDeadline: 'Termin bearbeiten',
      downloadDeadlinesIcs: 'ICS',
      downloadDeadlinesIcsAria: 'Alle Termine als Kalenderdatei (.ics) herunterladen',
      downloadDeadlinesIcsEmpty: 'Keine Termine mit festem Datum zum Kalender-Export.',
      openWorkspace: 'Arbeitsbereich öffnen',
      metricDrafts: 'Entwürfe',
      metricRisks: 'Risiken',
      metricDocuments: 'Dokumente',
      rfpBlockTitle: 'Ausschreibung',
      rfpBlockEmpty:
        'Lade eine Ausschreibung unter Dokumente hoch und starte die Analyse von dort.',
      steckbriefEmpty: 'Noch kein Steckbrief — starte die Analyse unter Dokumente.',
      lotsEmpty: 'Keine Lose in dieser Ausschreibung.',
      rfpAnalyzeCta: 'Zu Dokumenten',
      rfpReanalyzeHint: 'Neu analysieren empfohlen',
      documentsAnalyze: 'Analysieren',
      documentsQuickscan: 'Schnellprüfung',
      documentsQuickscanSuccess: 'Schnellprüfung fertig — Go/No-Bid steht.',
      documentsReanalyze: 'Neu analysieren',
      documentsAnalyzePending: 'Analyse läuft …',
      documentsAnalyzeSuccess: 'RFP-Analyse abgeschlossen.',
      documentsAnalyzeWhenReady:
        'Unterlagen hochgeladen — wenn alles da ist, unten einmal „Analysieren“ starten.',
      documentsAnalyzeReadyHint:
        'Alle Ausschreibungs-PDFs hochladen, dann einmal analysieren (verwendet das Dokument vom Typ „Ausschreibung“).',
      documentsAnalyzeFailed: 'RFP-Analyse fehlgeschlagen.',
      deleteDeal: 'Deal löschen',
      deleteDealConfirm: 'Deal endgültig löschen?',
      deleteDealDescription:
        'Der Deal, alle Dokumente, Fristen und Analyse-Daten werden unwiderruflich entfernt.',
      deleteDealPending: 'Wird gelöscht …',
      deleteDealSuccess: 'Deal gelöscht.',
      deleteDealFailed: 'Deal konnte nicht gelöscht werden.',
      documentsKindChangeAnalysisHint:
        'Analyse basiert auf einer früheren Ausschreibungs-Version dieses Dokuments.',
      metricAngebotsReife: 'Angebots-Reife',
      metricEligibility: 'Bietfähigkeit / Eignung',
      eligibilityTitle: 'Eignungs- und K.O.-Kriterien',
      eligibilityEmpty:
        'Keine strukturierten Eignungskriterien in der Analyse — ggf. neu analysieren.',
      eligibilityColCriterion: 'Kriterium',
      eligibilityColRequirement: 'Prüfung',
      eligibilityColStatus: 'Status',
      eligibilityMandatory: 'Pflicht',
      eligibilityVerdict: 'Gesamteinschätzung',
      eligibilityProfileCta: 'Fähigkeitsprofil ergänzen',
      risksTitle: 'Risiken & offene fachliche Themen',
      risksGeneralTitle: 'Allgemeine Risiken',
      risksGeneralEmpty: 'Keine kritischen Vertragsrisiken erkannt.',
      risksOpenPointsTitle: 'Offene Punkte: Fachlich',
      risksOpenPointsEmpty:
        'Keine offenen Punkte — alle Anforderungen fachlich abgedeckt.',
      risksRequestedEvidenceTitle: 'Vom Kunden angefragte Nachweise',
      risksRequestedEvidenceEmpty:
        'Keine fehlenden Nachweise erkannt — Eignungs- und Einreichungsanforderungen sind abgedeckt oder nicht extrahiert.',
      noticeExecutiveSummaryTitle: 'Executive Summary',
      proofSuggestedTitle: 'Vorgeschlagene Referenzen (noch nicht verknüpft)',
      proofSuggestedAdd: 'Zum Deal hinzufügen',
      risksSeverityCritical: 'Kritisch',
      risksSeverityHigh: 'Hoch',
      risksSeverityMedium: 'Mittel',
      recommendationAnalyzedOn: 'Analyse vom {date}',
      recommendationCoverage: 'Beweis vorhanden {percent}%',
      draftsTitle: 'Antwort-Entwürfe',
      draftsEmpty:
        'Noch keine Entwürfe — nach RFP-Analyse oder Neu-Analyse erscheinen sie hier.',
      draftsNoReference:
        'Keine verifizierte Referenz — Antwort kann nicht automatisch belegt werden.',
      draftsStatusReady: 'Bereit',
      draftsStatusDraft: 'Entwurf',
      draftsStatusGap: 'Lücke',
      draftsOpenDetail: 'Entwurf öffnen',
      draftsBackToEntry: 'Zurück zum Entwurf',
      draftsApplyToAnswer: 'In Antwort übernehmen',
      draftsKiDraftCta: 'KI-Entwurf',
      entryPanelBackToList: 'Zurück zur Liste',
      entryPanelEmpty: 'Wähle einen Eintrag aus der Liste.',
      risksOpenEntry: 'Risiko öffnen',
      draftsDetailTitle: 'Antwort-Entwurf',
      draftsAnswerLabel: 'Antwort',
      draftsAnswerEmpty: 'Noch kein Antworttext.',
      draftsSave: 'Speichern',
      draftsSaveSuccess: 'Antwort gespeichert.',
      draftsSaveFailed: 'Antwort konnte nicht gespeichert werden.',
      draftsCoveredCount: '{covered}/{total} Antwort bereit',
      draftsGapsCount: '{count} Lücken',
      briefingDialogTitle: 'Executive Briefing',
      briefingDialogDescription:
        'Kompakte Bid-Zusammenfassung für interne Freigabe (Management, ohne Qualification Call).',
      briefingCopyCta: 'Alles kopieren',
      briefingCopied: 'Executive Briefing in die Zwischenablage kopiert.',
      briefingCopyFailed: 'Kopieren fehlgeschlagen.',
      briefingPdfCta: 'Als PDF',
      briefingPdfPending: 'PDF wird erstellt …',
      briefingPdfSuccess: 'Executive Briefing als PDF heruntergeladen.',
      briefingPdfFailed: 'PDF-Export fehlgeschlagen.',
      metricIcpFit: 'ICP-Fit',
      documentsTitle: 'Dokumente',
      documentsEmpty:
        'Noch keine Dokumente — RFP, NDA, Vertrag, Angebot oder andere Dateien hochladen.',
      documentsUpload: 'Hochladen',
      documentsUploadTitle: 'Dokument hochladen',
      documentsKindLabel: 'Dokumenttyp',
      documentsDropzoneHint: 'Datei hierher ziehen oder klicken',
      documentsDropzoneReplace: 'Klicken oder ziehen zum Ersetzen',
      documentsDownload: 'Download',
      documentsRename: 'Umbenennen',
      documentsChangeKind: 'Typ ändern',
      documentsDelete: 'Löschen',
      documentsDeleteConfirm: 'Dokument endgültig löschen?',
      documentsRenameTitle: 'Dateiname',
    },
  },
  accounts: {
    searchCompaniesPlaceholder: 'Firma suchen …',
    addAccount: 'Account hinzufügen',
    importTemplateDownload: 'Excel-Vorlage herunterladen',
    importCancel: 'Abbrechen',
    importRemoveFile: 'Datei entfernen',
    importInvalidFile: 'Bitte eine CSV- oder Excel-Datei (.csv, .xlsx, .xls) wählen.',
    importInProgress: 'Import läuft …',
    importAccount: {
      title: 'Accounts importieren',
      description:
        'Pro Zeile reicht der Firmenname in Spalte A — Website, Branche, Standort, Logo und Mitarbeiterzahl werden beim Import per Brandfetch ergänzt. Weitere Spalten sind optional.',
      dropzoneTitle: 'CSV oder Excel hierher ziehen',
      dropzoneHint: 'oder klicken, um eine Datei vom Gerät zu wählen',
      fileSelectedHint: 'Klicken oder ziehen zum Ersetzen',
      submit: 'Importieren',
    },
    createDialogNameHint:
      'Firmennamen eingeben — Vorschläge aus euren Accounts, Partnern und Markendaten erscheinen beim Tippen.',
    createDialogSuggestLocal: 'Bereits angelegt',
    createDialogSuggestBrandfetch: 'Markenvorschlag',
    createDialogSearching: 'Suche nach Firmennamen …',
    createDialogTypeMore: 'Mindestens 2 Zeichen für die Namenssuche eingeben.',
    createDialogNoResults:
      'Keine Treffer für diesen Namen. Namen weiter ausformulieren oder unten manuell anlegen.',
    createDialogOpenExisting:
      'Dieser Account existiert bereits. Es wird zur Detailseite gewechselt.',
    quickCreateAccountTitle: 'Neuen Account anlegen',
    quickCreateAccountSubmit: 'Account anlegen und auswählen',
    quickCreateAccountHint:
      'Legt einen Account in deiner Organisation an und wählt ihn für diesen Deal aus.',
    filterNdaAll: 'Alle NDA-Zustände',
    filterNdaActive: 'NDA aktiv',
    filterNdaExpiring: 'NDA läuft ab',
    filterNdaNone: 'Kein NDA',
    filterLocation: 'Standort',
    lens: {
      briefingCta: 'Briefing erzeugen',
      emptyRead: 'Wähle links eine Firma aus.',
      proofsEmpty: 'Noch keine Beweise zu dieser Firma.',
      proofsLocked: 'Gesperrt',
      ndaNone: 'Kein NDA — Beweise nach ihrem Status verwendbar.',
      ndaActive: 'NDA aktiv — aus „teilbar“ wird gesperrt.',
      ndaExpiring: 'NDA läuft ab — aus „teilbar“ wird gesperrt.',
      signalHeading: 'Signal',
      dealsHeading: 'Offene Deals',
      proofsHeading: 'Beweise',
      briefing: {
        dialogSubtitle: 'Briefing',
        dialogLoading: 'Briefing wird geladen …',
        preparing: 'Wird vorbereitet …',
        sectionTalkingPoints: 'Gesprächsanker',
        sectionDeals: 'Deals im System',
        sectionSignals: 'Marktsignale',
        sectionRisks: 'Risiken & kritische News',
        sectionReferences: 'Passende Referenzen',
        sectionSignalRefMap: 'Signal → Referenz',
        noDeals: 'Kein Deal verknüpft — typisch für Erstgespräche.',
        noSignals: 'Keine aktuellen Signale zu diesem Account.',
        noReferences: 'Keine starken Referenz-Matches — Smart Match prüfen.',
        dealWithProof: 'mit Referenzbezug',
        dealNoProof: 'ohne Beweis',
        openAccount: 'Account öffnen',
        noAccount: 'Account noch nicht angelegt.',
        createAccount: 'Account anlegen',
      },
    },
  },
  dashboard: {
    searchReferencesPlaceholder: 'Referenzen suchen (Titel, Account, …)',
    moreFilters: 'Filter',
    columnsButton: 'Spalten',
    columnsReset: 'Zurück zur Voreinstellung',
    layoutList: 'Liste',
    layoutRead: 'Lesen',
    createManual: 'Manuell',
    createImport: 'Importieren',
    tooltipFavorites: 'Favoriten',
    tooltipStatus: 'Status',
    tooltipCreateReference: 'Referenz erstellen',
    home: {
      thinBanner:
        'Ehrliche Daten: Pre-Pilot — zu wenig Volumen für belastbare Zahlen. Arbeitsschlange bleibt, Kennzahlen erst mit echten Daten.',
      shellGreeting: 'Hallo',
      shellGreetingFallback: 'du',
      signalPillChance: 'Chance',
      signalPillRisk: 'Risiko',
      signalPillCritical: 'kritisch',
      statusCurrent: 'aktuell',
      statusExpiring: 'läuft ab',
      statusStale: 'veraltet',
      periodicQuarter: 'Quartal',
      salesRep: {
        subtitle: 'Deine Arbeit heute.',
        cta: 'Referenz finden',
        queueTitle: 'Braucht dich jetzt',
        queueDescription: 'Nach Dringlichkeit — was deine Deals heute voranbringt.',
        queueEmptyTitle: 'Leg los',
        queueEmptyDescription:
          'Verknüpfe deinen ersten Beweis mit einem offenen Deal — dann taucht hier deine Arbeitsschlange auf.',
        queueNoProof: 'kein Beweis',
        queueWeakProof: 'schwach belegt',
        queueFindProof: 'Beweis finden',
        queueHotSignal: 'heißes Signal',
        queueFollowUp: 'Nachfassen',
        queueSnoozeBack: 'Signale aus Snooze zurück',
        queueSnoozeDue: 'Wiedervorlage fällig',
        queueReview: 'Review Queue',
        dealOpen: 'offen',
        dealOverdue: 'überfällig',
        dealToday: 'heute',
        dealInOneDay: 'in 1 Tag',
        dealInDays: 'in {n} Tagen',
        dealInOneWeek: 'in 1 Wo',
        dealInWeeks: 'in {n} Wo',
        signalsTitle: 'Signale zu deinen Accounts',
        signalsDescription:
          'News und Positionswechsel bei deinen Accounts — jeweils mit passender Reaktion.',
        signalsEmptyTitle: 'Keine Signale',
        signalsEmptyDescription:
          'Noch keine überwachten Accounts — Watchlist einrichten.',
        coverageTitle: 'Deine offenen Deals — Beweis-Abdeckung',
        coverageDescription: 'Nach Frist sortiert. Deals ohne Beweis mit direktem Link.',
        coverageEmptyTitle: 'Noch keine Deals verknüpft',
        coverageEmptyDescription: '',
        coverageDonutSublabel: 'mit Beweis',
        coverageProofOk: 'Beweis ✓',
        coverageUntil: 'bis',
        coverageSignalCta: 'Beweis finden',
        coverageSignalBadge: 'Signal',
        reuseTitle: 'Was bei dir zieht',
        reuseDescription: 'Deine häufigsten Shares — Gewinner wiederverwenden.',
        reuseEmptyTitle: 'Noch nichts geteilt',
        reuseEmptyDescription: '',
        reuseFallbackTitle: 'Referenz',
        footerLabel: 'Diese Woche',
        footerMatches: '{n} Matches',
        footerShared: '{n} geteilt',
        footerDealsProof: '{withProof}/{total} Deals belegt',
        footerNoDeals: '0 Deals belegt',
        footerThinMatches: '0 Matches',
        footerThinShared: '0 geteilt',
        footerThinDeals: '0/0 Deals belegt',
      },
      accountManager: {
        subtitle: 'Was in deinem Portfolio Aufmerksamkeit braucht.',
        cta: 'Referenz erstellen',
        digestTitle: 'Wartet auf dich',
        digestDescription: 'Digest — was dich braucht.',
        digestEmptyTitle: 'Alles erledigt',
        digestEmptyDescription: 'Keine offenen Freigaben oder Anfragen.',
        digestApprovals: '{n} Referenzen warten auf deine Freigabe',
        digestApprovalsMeta: 'älteste seit {days} Tagen',
        digestApprovalsCta: 'freigeben',
        digestDealRequests: '{n} neue Referenz-Anfragen aus Deals',
        digestDealRequestsCta: 'bearbeiten',
        digestAdvocateWarn: 'Advocate-Warnung: {company}',
        digestAdvocateMeta: 'Fatigue-Schwelle erreicht',
        digestAdvocateCta: 'Quartal pausieren',
        freshTitle: 'Portfolio-Gesundheit — Frische',
        freshDescription: 'Was veraltet, läuft ab oder braucht Update?',
        freshEmptyTitle: 'Noch kein Portfolio',
        freshEmptyDescription: '',
        freshMore: '{n} weitere',
        freshMoreSub: 'aktuell',
        whitespotTitle: 'Weißflecken — was fehlt',
        whitespotDescription: 'Branchen/Themen ohne belastbare Referenz.',
        whitespotEmptyTitle: 'Noch keine Abdeckung',
        whitespotEmptyDescription: '',
        whitespotRequest: 'anfragen',
        funnelTitle: 'Freigabe-Durchsatz',
        funnelDescription: 'Wo stehen Referenzen im Flow?',
        funnelEmptyTitle: 'Noch keine Referenzen',
        funnelEmptyDescription: '',
        funnelDraft: 'Entwurf',
        funnelInternal: 'Intern geprüft',
        funnelCustomer: 'An Kunde',
        funnelApproved: 'Freigegeben',
        advocateTitle: 'Advocate-Last',
        advocateDescription: 'Wen frage ich wie oft?',
        advocateEmptyTitle: 'Noch keine Anfragen',
        advocateEmptyDescription: '',
        footerLabel: 'Dein Portfolio',
        footerReferences: '{n} Referenzen',
        footerPending: '{n} Freigaben offen',
        footerAdvocate: '{n} Advocate-Anfragen',
      },
      salesLeader: {
        subtitle: 'Was steht heute auf dem Plan?',
        cta: 'Team-Report',
        fixSync: 'Sync prüfen',
        riskTitle: 'Deals mit Risiko — Beweis-Abdeckung',
        riskDescription: 'Offene Deals nach Wert und Frist, bewertet nach Beweislage.',
        callQueueTitle: 'Jetzt anrufen',
        callQueueDescription:
          'Bis zu 5 Accounts mit Watchlist-Signal, offenem Deal und passendem Referenz-Beweis.',
        callQueueEmptyTitle: 'Keine priorisierten Anrufe',
        callQueueEmptyDescription:
          'Watchlist-Accounts mit aktivem Deal und frischem Marktsignal erscheinen hier.',
        callQueueColAccount: 'Account',
        callQueueColSignal: 'Signal',
        callQueueColReference: 'Passende Referenz',
        callQueueColWhy: 'Jetzt anrufen, weil',
        callQueueOpenDeal: 'Deal',
        callQueueOpenMatch: 'Match',
        callQueueSnooze: '1 Woche später',
        callQueueDone: 'Erledigt',
        callQueueRefScore: '{n} % Match',
        callQueueRefPersonHint: 'Bezug zur Person im Nachweis',
        callQueueNoRef: 'Noch kein starker Referenz-Match — im Deal prüfen.',
        whyChampion: 'Champion {name} auf deiner Watchlist — Relevanz für den Deal.',
        whyWatchlistAccount: 'Account auf der Watchlist mit frischem Signal.',
        whyRoleChange:
          'Führungswechsel — neuer Ansprechpartner und Neubewertung der Lage.',
        whyInitiative: 'Strategische Initiative passt zu eurem Angebot.',
        whyHiring: 'Neue Rolle/Stelle signalisiert Bedarf oder Budget.',
        whyPerfectRef: 'Starke Referenz für das Gespräch verfügbar.',
        whyPerfectRefPerson: 'Referenz-Nachweis mit Bezug zur betroffenen Person.',
        whyDealNoProof: 'Offener Deal ohne belastbaren Beweis — Signal als Hebel.',
        whyFallback: 'Zeitfenster durch Marktsignal und offene Pipeline.',
        riskEmptyTitle: 'Noch zu wenige Deals',
        riskEmptyDescription:
          'Eine belastbare Risiko-Sicht braucht mehr offene Deals im System.',
        riskNoProof: 'kein Beweis',
        riskPartial: 'teilweise',
        riskStrong: 'stark belegt',
        riskRequestRef: 'Referenz anfragen',
        riskReview: 'prüfen',
        covPipeTitle: 'Abdeckung vs. Pipeline',
        covPipeDescription: 'Wo verfolgen wir Deals, für die uns der Beweis fehlt?',
        covPipeEmptyTitle: 'Noch keine Pipeline-Abdeckung',
        covPipeEmptyDescription: '',
        signalRiskTitle: 'Signal-Risiko in der Pipeline',
        signalRiskDescription: 'Beziehungs- und Trigger-Risiko über offene Deals.',
        signalRiskEmptyTitle: 'Zu wenig Daten',
        signalRiskEmptyDescription:
          'Signal-Risiko braucht mehr überwachte Accounts und Deals.',
        signalRiskIntervene: 'eingreifen',
        signalRiskPushTeam: 'Team anstoßen',
        winTitle: 'Wirkungs-Beleg',
        winDescription: 'ROI-Beleg für die Leitung — bewusst periodisch, nicht operativ.',
        winEmptyTitle: 'Noch nicht aussagekräftig',
        winEmptyDescription:
          '{closed} abgeschlossene Deals (Schwelle: {min}). Kein Fake-Chart.',
        winWithRef: 'mit Referenz',
        winWithoutRef: 'ohne Referenz',
        winDelta: 'Δ +{n} Prozentpunkte Win-Rate',
        footerLabel: 'Org',
        footerReferences: '{n} Referenzen',
        footerActiveUsers: '{n} aktive Nutzer',
        footerShareRate: '{n}% Share-Rate',
      },
    },
  },
  marketSignals: {
    pageSubtitle: 'Live-Infos zu deinen Stakeholdern und Zielaccounts.',
    signalTypeExec: 'Executive',
    signalTypeCompany: 'Company',
    signalTypeMove: 'Move',
    executiveSection: 'Executive Tracking',
    newsSection: 'Company Update',
    manage: 'Verwalten',
    filterAccount: 'Account',
    filterAccountAll: 'Alle Accounts',
    filterAccountSearch: 'Account suchen …',
    filterChipAll: 'Alle',
    filterChipMove: 'Move',
    filterChipExecutive: 'Executive',
    filterChipCompany: 'Company',
    /** Personen auf der Executive-Watchlist (Verwalten → Executives). */
    filterContextChampions: 'Meine Executives',
    filterContextWithDeal: 'Mit Deal',
    sortRelevance: 'Relevanz',
    sortDate: 'Datum',
    lastUpdatedPrefix: 'Zuletzt aktualisiert',
    lastUpdatedNever: 'Noch nicht aktualisiert',
    briefingExecCount: '{count} Executive',
    briefingExecCountPlural: '{count} Executive',
    briefingCompanyCount: '{count} Firma',
    briefingCompanyCountPlural: '{count} Firmen',
    compellingEventLabel: 'Compelling Event',
    dealCountSingular: '{count} Deal',
    dealCountPlural: '{count} Deals',
    matchingRefsSingular: '1 passende Referenz',
    matchingRefsPlural: '{count} passende Referenzen',
    outreachCta: 'Outreach vorbereiten',
    outreachDialogTitle: 'Outreach-Entwurf',
    outreachCopy: 'Text kopieren',
    outreachCopied: 'Entwurf in die Zwischenablage kopiert.',
    outreachFailed: 'Outreach-Entwurf konnte nicht erstellt werden.',
    outreachMatchingRefsTitle: 'Passende Referenzen',
    outreachMatchingRefsEmpty: 'Keine passende Referenz gefunden.',
    outreachMatchingRefsHint:
      'Anhaken fügt einen kurzen Proof-Satz ein — ohne den Entwurf neu zu generieren.',
    outreachGenerating: 'Entwurf wird erstellt …',
    outreachClose: 'Schließen',
    menuHide: 'Ausblenden',
    menuMarkRead: 'Als gelesen',
    menuCopyLink: 'Link kopieren',
    menuLinkedIn: 'Auf LinkedIn suchen',
    linkCopied: 'Link kopiert.',
    linkMissing: 'Kein Quell-Link vorhanden.',
    feedsRefreshPending: 'Feeds werden abgerufen — das kann ein bis zwei Minuten dauern.',
    newBadge: 'Neu',
    openAccount: 'Account',
    sourcePrefix: 'Quelle',
    loadMore: '10 weitere anzeigen',
    emptyFollowingTitle: 'Noch keine Accounts in deiner Watchlist',
    emptyFollowingBody:
      'Lege Accounts und Zielpersonen fest, damit Signale hier erscheinen.',
    emptyFollowingCta: 'Accounts & Personen festlegen',
    feedEmptyTitle: 'Noch keine Signale',
    feedEmptyBody:
      'Sobald neue Signale zu deiner Watchlist vorliegen, erscheinen sie hier.',
  },
  commandPalette: {
    title: 'Command Palette',
    description: 'Suche nach Referenzen, Accounts oder Deals',
    placeholder: 'Suche nach Referenzen, Deals, Accounts…',
    searchLoading: 'Suche läuft…',
    searchEmpty: 'Keine Ergebnisse gefunden.',
    recents: 'Zuletzt besucht',
    noRecentsYet: 'Noch keine Einträge',
    actionNewReference: 'Neue Referenz erstellen',
    actionNewAccount: 'Account erstellen',
    /** Anzeige in der Suche, wenn keine Firma verknüpft ist */
    referenceNoAccountLabel: 'Kein Accountname vergeben',
  },
} as const

/** Tabellen: Auswahl-Zeile („3 von 10 Zeilen ausgewählt“). */
export function copyTableRowsSelected(selected: number, total: number) {
  return `${selected} von ${total} Ergebnissen ausgewählt`
}
